feat(prometheus) replace kong.tools.responses with raw ngx methods
Kong/kong-plugin-prometheus pull request #34
Opened 2018-12-14 13:05 UTC by kikito

`kong.tools.responses` is going to be removed from kong so I'm removing it from this plugin.

It didn't look like the `kong` global variable was available in the two files I modified, so I have used `ngx` methods instead.

2018-12-14 13:10 UTC, hishamhm commented
> It didn't look like the kong global variable was available in the two files I modified

What context are these files loaded from? The `kong` global variable should exist throughout the execution of the plugin.

2018-12-14 13:37 UTC, kikito commented
* `serve.lua` file is a stand-alone file thought to be included in a custom nginx template an "run by itself" (without Kong). So there I am quite sure that the kong global won't be available.

* The other one, `exporter.lua` is included from the handler, so it should indeed have kong.

I'm going to try using the variable in exporter. This plugin has tests, so it should fail if it's not possible

2018-12-16 17:03 UTC, hbagdi requested changes
@kikito 
The `0.3.x` releases are from `next` branch, because we run the CI against Kong's `next` branch.
Could you rebase this on top of next?
The `kong.tools.responses` is only in `serve.lua` in the `next` branch.

2018-12-17 22:11 UTC, hishamhm approved these changes
LGTM. `kong.tools.responses` is currently available in Kong `next` because that branch currently represents our aimed 0.15; the removal of deprecated concepts is happening in parallel in Kong `release/1.0.0` branch, which is next+removals.

2018-12-17 22:39 UTC, hbagdi commented
@hishamhm @kikito Thank you for the effort and eyes on this one!

2018-12-17 22:43 UTC, merged